// <auto-generated />
using System;
using System.Collections.Generic;
using Catalogo.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalogo.Data.EF.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    [Migration("20260904025931_RegistrarVideo")]
    partial class RegistrarVideo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalogo.Domain.Entity.CastFilme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CastFilmes");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Genero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("categoriasId")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.GenerosCategorias", b =>
                {
                    b.Property<int>("ID_CATEGORIA")
                        .HasColumnType("integer");

                    b.Property<int>("ID_GENERO")
                        .HasColumnType("integer");

                    b.Property<int>("Categoriaid")
                        .HasColumnType("integer");

                    b.Property<int>("Generoid")
                        .HasColumnType("integer");

                    b.HasKey("ID_CATEGORIA", "ID_GENERO");

                    b.HasIndex("Categoriaid");

                    b.HasIndex("Generoid");

                    b.ToTable("GenerosCategorias");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Media", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncodingCaminho")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("Videoid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Videoid")
                        .IsUnique();

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Video", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("CastsFilme")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("Categorias")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("Duracao")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Generos")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.VideoCastFilme", b =>
                {
                    b.Property<int>("ID_CAST_FILME")
                        .HasColumnType("integer");

                    b.Property<int>("ID_VIDEO")
                        .HasColumnType("integer");

                    b.HasKey("ID_CAST_FILME", "ID_VIDEO");

                    b.ToTable("VideoCastFilme");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.VideoCategoria", b =>
                {
                    b.Property<int>("ID_CATEGORIA")
                        .HasColumnType("integer");

                    b.Property<int>("ID_VIDEO")
                        .HasColumnType("integer");

                    b.HasKey("ID_CATEGORIA", "ID_VIDEO");

                    b.ToTable("VideoCategoria");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.GenerosCategorias", b =>
                {
                    b.HasOne("Catalogo.Domain.Entity.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("Categoriaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalogo.Domain.Entity.Genero", "Genero")
                        .WithMany("_categorias")
                        .HasForeignKey("Generoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Media", b =>
                {
                    b.HasOne("Catalogo.Domain.Entity.Video", null)
                        .WithOne("Trailer")
                        .HasForeignKey("Catalogo.Domain.Entity.Media", "Videoid");

                    b.HasOne("Catalogo.Domain.Entity.Video", null)
                        .WithOne("Media")
                        .HasForeignKey("Catalogo.Domain.Entity.Media", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Video", b =>
                {
                    b.OwnsOne("Catalogo.Domain.ValueObject.Image", "Thumb", b1 =>
                        {
                            b1.Property<int>("Videoid")
                                .HasColumnType("integer");

                            b1.Property<string>("caminho")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ThumbCaminho");

                            b1.HasKey("Videoid");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("Videoid");
                        });

                    b.OwnsOne("Catalogo.Domain.ValueObject.Image", "ThumbHalf", b1 =>
                        {
                            b1.Property<int>("Videoid")
                                .HasColumnType("integer");

                            b1.Property<string>("caminho")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ThumbHalfCaminho");

                            b1.HasKey("Videoid");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("Videoid");
                        });

                    b.OwnsOne("Catalogo.Domain.ValueObject.Image", "banner", b1 =>
                        {
                            b1.Property<int>("Videoid")
                                .HasColumnType("integer");

                            b1.Property<string>("caminho")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BannerCaminho");

                            b1.HasKey("Videoid");

                            b1.ToTable("Videos");

                            b1.WithOwner()
                                .HasForeignKey("Videoid");
                        });

                    b.Navigation("Thumb");

                    b.Navigation("ThumbHalf");

                    b.Navigation("banner");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Genero", b =>
                {
                    b.Navigation("_categorias");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Video", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Trailer");
                });
#pragma warning restore 612, 618
        }
    }
}
