// <auto-generated />
using System;
using System.Collections.Generic;
using Catalogo.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalogo.Data.EF.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    partial class CatalogoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalogo.Domain.Entity.CastFilme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CastFilmes");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Genero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("categoriasId")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.GenerosCategorias", b =>
                {
                    b.Property<int>("ID_CATEGORIA")
                        .HasColumnType("integer");

                    b.Property<int>("ID_GENERO")
                        .HasColumnType("integer");

                    b.Property<int>("Categoriaid")
                        .HasColumnType("integer");

                    b.Property<int>("Generoid")
                        .HasColumnType("integer");

                    b.HasKey("ID_CATEGORIA", "ID_GENERO");

                    b.HasIndex("Categoriaid");

                    b.HasIndex("Generoid");

                    b.ToTable("GenerosCategorias");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.GenerosCategorias", b =>
                {
                    b.HasOne("Catalogo.Domain.Entity.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("Categoriaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalogo.Domain.Entity.Genero", "Genero")
                        .WithMany("_categorias")
                        .HasForeignKey("Generoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Catalogo.Domain.Entity.Genero", b =>
                {
                    b.Navigation("_categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
